Import full name: `importlib.resources`
When I upgraded to Python 3.14, I noticed failures of the following kind
when attempting to build Triton and run tutorials:

```
AttributeError: module 'importlib' has no attribute 'resources'
```

This seemed quite strange, since the [importlib.resources] package is
certainly a part of 3.14. The trick is to import the full name of the
Python module: `import importlib.resources`.

[importlib.resources]: https://docs.python.org/3.14/library/importlib.resources.html